### ISSUE TITLE
The problem with depth calculation

### ISSUE THREAD

**Issue by Shatur** [BastiaanOlij/shader_tutorial#6]
Thank you a lot for the tutorial!
But I noticed that the cuve is rendered twice. The problem disappears if I remove the albedo and emisson multiplication by `ALPHA` (but water depth will be lost). It also works if use constant value for `ALPHA` It looks like the problem in depth calculation.
![изображение](https://user-images.githubusercontent.com/22453358/80916451-6a1f4600-8d61-11ea-9529-ac270bb9b074.png)

**Comment by Shatur** [comment]
I [solved](https://github.com/Zoriya/zoriya/commit/f83d55a427651e366d559eaa24f6e2d03abbd4a7) it in my low poly water by dividing refraction UV by `PROJECTION_MATRIX[2][2]` and `VERTEX.z`.

**Comment by BastiaanOlij** [comment]
Glad to hear you found what was wrong :)
